# Generated by Django 6.0.1 on 2026-01-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='image',
            field=models.ImageField(upload_to='vegpic/'),
        ),
    ]
